<a href="https://colab.research.google.com/github/bilalamove/Nabila-psd-m5/blob/main/Nabila_PSD_m5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd
import numpy as np

In [11]:
# Membaca dataset
df = pd.read_csv('paket_a_transaksi_pos_2024_2025.csv')

# Menampilkan 5 baris pertama
df.head()

,id_transaksi,tanggal,kode_gerai,kode_kasir,kode_produk,jumlah,harga_satuan,diskon_persen,status
0,TRX0241065,2025-06-02,G09,K011,RMT1402,4,13000,0,SELESAI
1,TRX0240510,2024-12-28,G09,K015,SGR1205,1,21000,0,SELESAI
2,TRX0244483,2024-09-04,G11,K029,RMT1407,3,"7500,00",0,SELESAI
3,TRX0242532,2025-07-30,G05,K001,MKN1103,2,6500,0,SELESAI
4,TRX0243509,26/03/2025,G05,K016,RMT1407,1,6000,0,SELESAI

In [12]:
# Menampilkan informasi struktur dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5030 entries, 0 to 5029
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_transaksi   5030 non-null   object
 1   tanggal        5030 non-null   object
 2   kode_gerai     5030 non-null   object
 3   kode_kasir     4769 non-null   object
 4   kode_produk    5030 non-null   object
 5   jumlah         5030 non-null   int64
 6   harga_satuan   5030 non-null   object
 7   diskon_persen  5030 non-null   int64
 8   status         5030 non-null   object
dtypes: int64(2), object(7)
memory usage: 353.8+ KB

In [13]:
# Menampilkan jumlah baris dan kolom
print("Jumlah baris dan kolom:", df.shape)

# Menampilkan nama seluruh kolom
print("\nNama kolom:")
print(df.columns.tolist())

Jumlah baris dan kolom: (5030, 9)

Nama kolom:
['id_transaksi', 'tanggal', 'kode_gerai', 'kode_kasir', 'kode_produk', 'jumlah', 'harga_satuan', 'diskon_persen', 'status']

In [14]:
# Menghitung jumlah missing value setiap kolom
missing = df.isnull().sum()

print("Jumlah Missing Value:")
print(missing)

# Menampilkan kolom yang memiliki missing value
print("\nKolom yang memiliki Missing Value:")
print(missing[missing > 0])

Jumlah Missing Value:
id_transaksi       0
tanggal            0
kode_gerai         0
kode_kasir       261
kode_produk        0
jumlah             0
harga_satuan       0
diskon_persen      0
status             0
dtype: int64

Kolom yang memiliki Missing Value:
kode_kasir    261
dtype: int64

In [15]:
# Mengisi kode kasir yang kosong
df['kode_kasir'] = df['kode_kasir'].fillna('TIDAK DIKETAHUI')

# Menghapus baris yang memiliki data penting kosong
kolom_penting = [
    'tanggal',
    'jumlah',
    'harga_satuan',
    'diskon_persen',
    'status'
]

df = df.dropna(subset=kolom_penting)

# Menghapus data duplikat
df = df.drop_duplicates()

print("Missing Value setelah penanganan:")
print(df.isnull().sum())

Missing Value setelah penanganan:
id_transaksi     0
tanggal          0
kode_gerai       0
kode_kasir       0
kode_produk      0
jumlah           0
harga_satuan     0
diskon_persen    0
status           0
dtype: int64

In [16]:
# Mengubah kolom tanggal menjadi datetime
df['tanggal'] = pd.to_datetime(
    df['tanggal'],
    errors='coerce'
)

# Mengubah kolom numerik
kolom_numerik = [
    'jumlah',
    'harga_satuan',
    'diskon_persen'
]

for kolom in kolom_numerik:
    df[kolom] = pd.to_numeric(
        df[kolom],
        errors='coerce'
    )

# Menghapus data yang gagal dikonversi
df = df.dropna(
    subset=['tanggal', 'jumlah', 'harga_satuan', 'diskon_persen']
)

# Menampilkan tipe data terbaru
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4764 entries, 0 to 5029
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_transaksi   4764 non-null   object
 1   tanggal        4764 non-null   datetime64[ns]
 2   kode_gerai     4764 non-null   object
 3   kode_kasir     4764 non-null   object
 4   kode_produk    4764 non-null   object
 5   jumlah         4764 non-null   int64
 6   harga_satuan   4764 non-null   float64
 7   diskon_persen  4764 non-null   int64
 8   status         4764 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(2), object(5)
memory usage: 372.2+ KB

In [17]:
# Menyeragamkan penulisan status
df['status'] = df['status'].astype(str).str.strip().str.upper()

# Melihat jumlah masing-masing status
print(df['status'].value_counts())

# Melihat status yang tersedia
print("\nStatus transaksi:")
print(df['status'].unique())

status
SELESAI    4497
BATAL       183
RETUR        84
Name: count, dtype: int64

Status transaksi:
['SELESAI' 'BATAL' 'RETUR']

In [18]:
# Menampilkan informasi diskon
print("Diskon terendah:", df['diskon_persen'].min())
print("Diskon tertinggi:", df['diskon_persen'].max())

# Memeriksa diskon yang tidak valid
print("\nDiskon di luar rentang 0-100:")
print(df[
    (df['diskon_persen'] < 0) |
    (df['diskon_persen'] > 100)
])

Diskon terendah: 0
Diskon tertinggi: 20

Diskon di luar rentang 0-100:
Empty DataFrame
Columns: [id_transaksi, tanggal, kode_gerai, kode_kasir, kode_produk, jumlah, harga_satuan, diskon_persen, status]
Index: []

In [19]:
# Menghapus transaksi dengan diskon tidak valid
df = df[
    (df['diskon_persen'] >= 0) &
    (df['diskon_persen'] <= 100)
].copy()

# Menghitung nilai transaksi sebelum diskon
df['total_harga'] = (
    df['jumlah'] * df['harga_satuan']
)

# Menghitung nilai setelah diskon
df['nilai_setelah_diskon'] = (
    df['total_harga'] *
    (1 - df['diskon_persen'] / 100)
)

# Membulatkan hasil menjadi dua angka desimal
df['nilai_setelah_diskon'] = (
    df['nilai_setelah_diskon'].round(2)
)

# Menampilkan hasil perhitungan
df[[
    'jumlah',
    'harga_satuan',
    'diskon_persen',
    'total_harga',
    'nilai_setelah_diskon'
]].head(10)

    jumlah  harga_satuan  diskon_persen  total_harga  nilai_setelah_diskon
0        4     13,000.00              0    52,000.00             52,000.00
1        1     21,000.00              0    21,000.00             21,000.00
3        2      6,500.00              0    13,000.00             13,000.00
5       12     45,500.00             10   546,000.00            491,400.00
6        1     18,000.00              0    18,000.00             18,000.00
7        4     47,500.00             10   190,000.00            171,000.00
9        2      6,500.00              0    13,000.00             13,000.00
10       4     33,500.00             10   134,000.00            120,600.00
11       2     30,500.00              0    61,000.00             61,000.00
12       1     11,500.00             20    11,500.00              9,200.00

In [20]:
# Menghitung pendapatan bersih berdasarkan status
df['pendapatan_bersih'] = np.select(
    [
        df['status'] == 'SELESAI',
        df['status'] == 'RETUR',
        df['status'] == 'BATAL'
    ],
    [
        df['nilai_setelah_diskon'],
        -df['nilai_setelah_diskon'],
        0
    ],
    default=np.nan
)

# Menghapus status yang tidak dikenal
df = df.dropna(subset=['pendapatan_bersih'])

# Menampilkan hasil
df[[
    'status',
    'total_harga',
    'diskon_persen',
    'nilai_setelah_diskon',
    'pendapatan_bersih'
]].head(15)

,status,total_harga,diskon_persen,nilai_setelah_diskon,pendapatan_bersih
0,SELESAI,"52,000.00",0,"52,000.00","52,000.00"
1,SELESAI,"21,000.00",0,"21,000.00","21,000.00"
3,SELESAI,"13,000.00",0,"13,000.00","13,000.00"
5,SELESAI,"546,000.00",10,"491,400.00","491,400.00"
6,SELESAI,"18,000.00",0,"18,000.00","18,000.00"
7,SELESAI,"190,000.00",10,"171,000.00","171,000.00"
9,BATAL,"13,000.00",0,"13,000.00",0.00
10,SELESAI,"134,000.00",10,"120,600.00","120,600.00"
11,SELESAI,"61,000.00",0,"61,000.00","61,000.00"
12,SELESAI,"11,500.00",20,"9,200.00","9,200.00"
13,SELESAI,"27,000.00",0,"27,000.00","27,000.00"
14,SELESAI,"7,500.00",0,"7,500.00","7,500.00"
15,SELESAI,"22,000.00",0,"22,000.00","22,000.00"
16,SELESAI,"11,500.00",0,"11,500.00","11,500.00"
17,SELESAI,"294,000.00",0,"294,000.00","294,000.00"

In [21]:
# Mengambil tahun dari kolom tanggal
df['tahun'] = df['tanggal'].dt.year

# Melihat jumlah transaksi berdasarkan tahun
print(df['tahun'].value_counts().sort_index())

tahun
2024    2377
2025    2387
Name: count, dtype: int64

In [22]:
# Memilih data tahun 2024 dan 2025
df_tahunan = df[
    df['tahun'].isin([2024, 2025])
]

# Menghitung total pendapatan bersih per tahun
pendapatan_tahunan = (
    df_tahunan
    .groupby('tahun')['pendapatan_bersih']
    .sum()
    .reindex([2024, 2025], fill_value=0)
    .reset_index()
)

# Mengubah nama kolom
pendapatan_tahunan.columns = [
    'Tahun',
    'Total Pendapatan Bersih'
]

# Menampilkan hasil
print("TOTAL PENDAPATAN PER TAHUN")
display(pendapatan_tahunan)

TOTAL PENDAPATAN PER TAHUN

   Tahun  Total Pendapatan Bersih
0   2024           378,222,392.90
1   2025           236,635,494.89

In [23]:
# Mengambil nilai pendapatan masing-masing tahun
pendapatan_2024 = pendapatan_tahunan.loc[
    pendapatan_tahunan['Tahun'] == 2024,
    'Total Pendapatan Bersih'
].iloc[0]

pendapatan_2025 = pendapatan_tahunan.loc[
    pendapatan_tahunan['Tahun'] == 2025,
    'Total Pendapatan Bersih'
].iloc[0]

# Menghitung selisih pendapatan
selisih = pendapatan_2025 - pendapatan_2024

print("Pendapatan 2024 : Rp{:,.2f}".format(pendapatan_2024))
print("Pendapatan 2025 : Rp{:,.2f}".format(pendapatan_2025))
print("Selisih         : Rp{:,.2f}".format(selisih))

# Menghitung persentase perubahan
if pendapatan_2024 != 0:
    persentase = (selisih / pendapatan_2024) * 100
    print("Perubahan       : {:.2f}%".format(persentase))
else:
    print("Perubahan       : Tidak dapat dihitung")

Pendapatan 2024 : Rp378,222,392.90
Pendapatan 2025 : Rp236,635,494.89
Selisih         : Rp-141,586,898.01
Perubahan       : -37.43%

In [24]:
# Menampilkan 10 data transaksi setelah dibersihkan
display(df.head(10))

# Menampilkan informasi dataset setelah pembersihan
df.info()

,id_transaksi,tanggal,kode_gerai,kode_kasir,kode_produk,jumlah,harga_satuan,diskon_persen,status,total_harga,nilai_setelah_diskon,pendapatan_bersih,tahun
0,TRX0241065,2025-06-02,G09,K011,RMT1402,4,"13,000.00",0,SELESAI,"52,000.00","52,000.00","52,000.00",2025
1,TRX0240510,2024-12-28,G09,K015,SGR1205,1,"21,000.00",0,SELESAI,"21,000.00","21,000.00","21,000.00",2024
3,TRX0242532,2025-07-30,G05,K001,MKN1103,2,"6,500.00",0,SELESAI,"13,000.00","13,000.00","13,000.00",2025
5,TRX0240658,2025-07-18,G01,K008,RMT1408,12,"45,500.00",10,SELESAI,"546,000.00","491,400.00","491,400.00",2025
6,TRX0244581,2025-09-24,G10,K021,MIN1004,1,"18,000.00",0,SELESAI,"18,000.00","18,000.00","18,000.00",2025
7,TRX0241251,2024-10-09,G09,K035,SGR1204,4,"47,500.00",10,SELESAI,"190,000.00","171,000.00","171,000.00",2024
9,TRX0243163,2024-03-22,G08,K028,PRW1304,2,"6,500.00",0,BATAL,"13,000.00","13,000.00",0.00,2024
10,TRX0243788,2024-04-19,G11,K040,MKN1107,4,"33,500.00",10,SELESAI,"134,000.00","120,600.00","120,600.00",2024
11,TRX0240372,2024-04-11,G11,K034,BYI1506,2,"30,500.00",0,SELESAI,"61,000.00","61,000.00","61,000.00",2024
12,TRX0244786,2025-11-02,G01,K024,SGR1207,1,"11,500.00",20,SELESAI,"11,500.00","9,200.00","9,200.00",2025

<class 'pandas.core.frame.DataFrame'>
Index: 4764 entries, 0 to 5029
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_transaksi          4764 non-null   object
 1   tanggal               4764 non-null   datetime64[ns]
 2   kode_gerai            4764 non-null   object
 3   kode_kasir            4764 non-null   object
 4   kode_produk           4764 non-null   object
 5   jumlah                4764 non-null   int64
 6   harga_satuan          4764 non-null   float64
 7   diskon_persen         4764 non-null   int64
 8   status                4764 non-null   object
 9   total_harga           4764 non-null   float64
 10  nilai_setelah_diskon  4764 non-null   float64
 11  pendapatan_bersih     4764 non-null   float64
 12  tahun                 4764 non-null   int32
dtypes: datetime64[ns](1), float64(4), int32(1), int64(2), object(5)
memory usage: 502.5+ KB

In [25]:
# Menyimpan dataset yang sudah dibersihkan
df.to_csv(
    'transaksi_pos_bersih.csv',
    index=False
)

print("Dataset bersih berhasil disimpan!")

Dataset bersih berhasil disimpan!

In [26]:
# Menyimpan rekap pendapatan tahunan
pendapatan_tahunan.to_csv(
    'rekap_pendapatan_tahunan.csv',
    index=False
)

print("Rekap pendapatan tahunan berhasil disimpan!")

Rekap pendapatan tahunan berhasil disimpan!